version: '1.0.{build}'

image: Visual Studio 2017
configuration: Release


before_build:
- ps: nuget restore

build:
  verbosity: minimal

after_build:
  7z a PaperDownload.zip %APPVEYOR_BUILD_FOLDER%\PaperDownloader\bin\Release



artifacts:
  path: PaperDownload.zip
  name: PaperDownload

skip_commits:
  files:
    - Screenshots/*
    - '**/*.md'
    
deploy:
  #release: PaperDownload-v$(appveyor_build_version)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: 2ZjNMlRALutd+9SLwQrQljeBdTAlf+YCrMy66K6iEu6KNDhF9G0Bv5DgBnNL5zJM # your encrypted token from GitHub
  artifact: PaperDownload.zip          # upload all files form release
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only