version: '{build}'

image: Visual Studio 2017
configuration: Release


before_build:
- ps: nuget restore

build:
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
after_build:
  7z a PaperDownload.zip %APPVEYOR_BUILD_FOLDER%\PaperDownloader\bin\Release
deploy:
  release: PaperDownload-v$(appveyor_build_version)
  description: 'Download paper jars with ease'
  provider: GitHub
  auth_token:
    secure: 2ZjNMlRALutd+9SLwQrQljeBdTAlf+YCrMy66K6iEu6KNDhF9G0Bv5DgBnNL5zJM # your encrypted token from GitHub
  artifact: bin/Release            # upload all files form release
  draft: false
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true
    branch: master                 # release from master branch only
